version: "3"

services:
  database:
    image: postgres:14
    env_file:
      - .env
    environment:
     - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
    ports:
      - "5432:5432"

  {{cookiecutter.project_name}}:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: uvicorn main:api --host ${HOST} --port ${PORT} --reload
    working_dir: /workspace
    volumes:
      - "./{{cookiecutter.project_name}}:/workspace"
    depends_on:
     - database
    env_file:
      - .env
    ports:
      - "80:80"