version: "3"

services:
  database:
    image: postgres:14
    env_file:
      - .env
    environment:
     - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
    ports:
      - "5432:5432"

  {{cookiecutter.project_name}}:
    build: .
    command: uvicorn main:api --host ${HOST} --port ${PORT}
    depends_on:
     - database
    environment:
      - "PRODUCTION=TRUE"
    env_file:
      - .env
    ports:
      - "80:80"